# Generated by Django 5.1.1 on 2024-09-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='images/shirt.jpeg', upload_to='images/'),
        ),
    ]
