# Generated by Django 5.1.1 on 2024-09-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='static/images/shirt.jpeg', upload_to='static/images'),
        ),
    ]
